package coffeshop;

import OperationPackages.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;

public class BillTotal extends javax.swing.JFrame {

    public BillTotal() {
        super("Bill details");
        initComponents();
         initBranches();
    }
     ArrayList<Branches> list;
    void initBranches()
    {
        list=Branches.selectAll();
        for (int i = 0; i < list.size(); i++) {
            jComboBox_branches.addItem(list.get(i).getCity());
        }
    }
     Bill order;
      ArrayList<BillDetails> arrayList;
      String result="";
   void initBill(int branch,int cust,String addresss)
    {
        result="";
         long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis);  
       
         order=new Bill();
        order.setTax(0);
        order.setBillNo(branch);
        order.setCustId(cust);
        
        order.setPurchaseDate(date);
        double total=0;
       
         arrayList=new ArrayList<>();
         for (int i = 0; i < OperationsGlobals.CartProds.size(); i++) {
             
           BillDetails det=new BillDetails(0, 0,OperationsGlobals.CartProds.get(i).getProductNo(),OperationsGlobals.CartProds.get(i).productsQuantity);
           arrayList.add(det);
           result+="Name: "+OperationsGlobals.CartProds.get(i).getProductName()+"\t Price: "+
                 OperationsGlobals.CartProds.get(i).getPrice()+"\t Quantity: "+
                 OperationsGlobals.CartProds.get(i).productsQuantity +"\n";  
           
           
           total+=OperationsGlobals.CartProds.get(i).getPrice()*OperationsGlobals.CartProds.get(i).productsQuantity;
        }

      
       
          Date date1 = new Date();  
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
       
        result+= "User Name: "+OperationsGlobals.userCoffe.getCustomerName()+"\n";
        result+= "Order Date : " +formatter.format(date1)   +"\n";
        
    
        
    
      result+= "Total without tax : " +total   +"\n";
      
       if(total>100)
     {
         order.setTax(total*0.25);
          result+= "Tax  : " +order.getTax()  +"\n";
          result+= "Total with tax  : " +(order.getTax()+total)  +"\n";
     }
     order.setTotal(total);
      jTextArea_total.setText(result);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblPanelwsx = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        address_txt = new javax.swing.JTextField();
        jComboBox_branches = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        jButton_submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_signup3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_total = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPanelwsx.setBackground(new java.awt.Color(237, 232, 207));
        tblPanelwsx.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("ADDRESS");
        tblPanelwsx.add(jLabel2);
        jLabel2.setBounds(20, 90, 140, 29);

        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });
        tblPanelwsx.add(address_txt);
        address_txt.setBounds(140, 80, 440, 110);

        jComboBox_branches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_branchesActionPerformed(evt);
            }
        });
        tblPanelwsx.add(jComboBox_branches);
        jComboBox_branches.setBounds(140, 20, 440, 42);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Branch");
        tblPanelwsx.add(jLabel11);
        jLabel11.setBounds(30, 20, 110, 29);

        jButton_submit.setBackground(new java.awt.Color(255, 255, 255));
        jButton_submit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_submit.setText("Show Total");
        jButton_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitActionPerformed(evt);
            }
        });
        tblPanelwsx.add(jButton_submit);
        jButton_submit.setBounds(140, 200, 440, 50);

        getContentPane().add(tblPanelwsx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 770, 270));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        jLabel1.setText("Thank you..");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 380, 70));

        jButton_signup3.setBackground(new java.awt.Color(255, 255, 255));
        jButton_signup3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_signup3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffeshop/home.png"))); // NOI18N
        jButton_signup3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_signup3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_signup3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, 60));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea_total.setColumns(20);
        jTextArea_total.setRows(5);
        jScrollPane1.setViewportView(jTextArea_total);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 540, 170));

        saveButton.setText("submit");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel2.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 150, 40));

        jButton2.setText("Save to File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 150, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 600, 250));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffeshop/back_medum.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -160, -1, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_signup3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_signup3ActionPerformed
        // TODO add your handling code here:
        Operations.OpenNew(this, new HomePage());
    }//GEN-LAST:event_jButton_signup3ActionPerformed

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void jComboBox_branchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_branchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_branchesActionPerformed

    private void jButton_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitActionPerformed
        // TODO add your handling code here:
        if (address_txt.getText().toString().equals(""))
                {
            Operations.openRequied();
        } else {
         int branch=list.get(jComboBox_branches.getSelectedIndex()).getBranchNo();
         int custId=OperationsGlobals.userCoffe.getCustomerID();
         String address=address_txt.getText().toString();
         initBill(branch,custId,address);
        }
    }//GEN-LAST:event_jButton_submitActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
       int id= order.AddBill();
        for (int i = 0; i < arrayList.size(); i++) {
            arrayList.get(i).AddNew(id);
        }
        OperationsGlobals.CartProds=null;
        Operations.SuccessAddedOrder();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           BufferedWriter writer = null;
        try {
            writer = new BufferedWriter(new FileWriter("./MyBill.txt"));
            writer.write("Bill Details\n");
            writer.write("**************************************\n");
             writer.write(result+"\n");
             Operations.SuccessSaved("Data Exported To MyBill in project directory");
        } catch (IOException e) {
            System.err.println(e);
        } finally {
            if (writer != null) {
                try {
                    writer.close();
                } catch (IOException e) {
                    System.err.println(e);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BillTotal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_txt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_signup3;
    private javax.swing.JButton jButton_submit;
    private javax.swing.JComboBox<String> jComboBox_branches;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_total;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel tblPanelwsx;
    // End of variables declaration//GEN-END:variables
}
