package coffeshop;

import OperationPackages.Operations;
import OperationPackages.OperationsGlobals;
import OperationPackages.Products;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JSpinner;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class BillFrame extends javax.swing.JFrame {

    public BillFrame() {
        super("Cart window");
        initComponents();
        initProducts();
    }
    void UpdateCart(int value,Products products)
    {
         for (int i = 0; i < OperationsGlobals.CartProds.size(); i++) {
              if(products.getProductNo()==OperationsGlobals.CartProds.get(i).getProductNo())
              {
               products.productsQuantity=value;
              }
          }
    }
    void initProducts()
    {
      

final GridBagConstraints c = new GridBagConstraints();

c.weightx = 1;
c.weighty = 1;
c.fill = GridBagConstraints.BOTH;
c.gridy = 0;
        
        for (int j = 0; j < OperationsGlobals.CartProds.size(); j++) {
            
        
       JButton jb=new JButton( OperationsGlobals.CartProds.get(j).getProductName());
               jb.setBackground(Color.ORANGE);
               jb.setSize(50,50);
        pane.add(jb, c);  
      final  Products p=OperationsGlobals.CartProds.get(j);
           final JSpinner jSpinner=new JSpinner();
           if(p.productsQuantity!=0)
               jSpinner.setValue(p.productsQuantity);
            jSpinner.addChangeListener(new ChangeListener() {

                @Override
                public void stateChanged(ChangeEvent e) {
                    int val=Integer.parseInt( jSpinner.getValue().toString());
                UpdateCart(val ,p);
                }
            });
            pane.add(jSpinner, c);
           c.gridy++;
        }
         
         
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblPanelwsx = new javax.swing.JPanel();
        pane = new javax.swing.JPanel();
        jButton_submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_signup4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPanelwsx.setBackground(new java.awt.Color(237, 232, 207));
        tblPanelwsx.setLayout(null);

        pane.setBackground(new java.awt.Color(237, 232, 207));
        pane.setLayout(new java.awt.GridBagLayout());
        tblPanelwsx.add(pane);
        pane.setBounds(0, 30, 750, 380);

        jButton_submit.setBackground(new java.awt.Color(255, 255, 255));
        jButton_submit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_submit.setText("Submit");
        jButton_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitActionPerformed(evt);
            }
        });
        tblPanelwsx.add(jButton_submit);
        jButton_submit.setBounds(200, 440, 350, 37);

        getContentPane().add(tblPanelwsx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 770, 550));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        jLabel1.setText("Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 320, 100));

        jButton_signup4.setBackground(new java.awt.Color(255, 255, 255));
        jButton_signup4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_signup4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffeshop/home.png"))); // NOI18N
        jButton_signup4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_signup4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_signup4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffeshop/back_medum.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -160, -1, 940));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitActionPerformed
        // TODO add your handling code here:
        
        Operations.OpenNew(this, new BillTotal());
    }//GEN-LAST:event_jButton_submitActionPerformed

    private void jButton_signup4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_signup4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_signup4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BillFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_signup4;
    private javax.swing.JButton jButton_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pane;
    private javax.swing.JPanel tblPanelwsx;
    // End of variables declaration//GEN-END:variables
}
