package coffeshop;

import OperationPackages.Customer;
import OperationPackages.Operations;
import OperationPackages.UserCoffe;
import java.sql.SQLException;

public class Signup extends javax.swing.JFrame {

  
    public Signup() {
        super("SignUp window");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_UserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jComboBox_city = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton_male = new javax.swing.JRadioButton();
        jRadioButton_female = new javax.swing.JRadioButton();
        jButton_signup = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton_signup2 = new javax.swing.JButton();
        jButton_signup1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        jLabel1.setText("Sign up");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 0, 320, 100);

        jPanel2.setBackground(new java.awt.Color(237, 232, 207));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 126, 29);

        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_name);
        jTextField_name.setBounds(210, 10, 254, 38);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("UserName");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 60, 180, 29);
        jPanel2.add(jTextField_UserName);
        jTextField_UserName.setBounds(210, 60, 254, 38);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 110, 180, 29);

        jPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_passwordActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField_password);
        jPasswordField_password.setBounds(210, 110, 260, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Phone Number");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 160, 198, 29);

        jTextField_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phoneActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_phone);
        jTextField_phone.setBounds(210, 160, 260, 38);

        jComboBox_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dammam", "Dhahran", "Riyadh", " " }));
        jComboBox_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_cityActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox_city);
        jComboBox_city.setBounds(210, 220, 254, 42);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("City");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 230, 126, 29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("If You have account ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 340, 250, 29);

        jRadioButton_male.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton_male.setText("Male");
        jRadioButton_male.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton_maleMouseClicked(evt);
            }
        });
        jRadioButton_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_maleActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton_male);
        jRadioButton_male.setBounds(210, 280, 71, 29);

        jRadioButton_female.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton_female.setText("Female");
        jRadioButton_female.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton_femaleMouseClicked(evt);
            }
        });
        jRadioButton_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_femaleActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton_female);
        jRadioButton_female.setBounds(300, 280, 133, 29);

        jButton_signup.setBackground(new java.awt.Color(255, 255, 255));
        jButton_signup.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_signup.setText("Log In");
        jButton_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_signupActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_signup);
        jButton_signup.setBounds(260, 340, 120, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Gender");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 280, 162, 29);

        jButton_signup2.setBackground(new java.awt.Color(255, 255, 255));
        jButton_signup2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_signup2.setText("Sign Up");
        jButton_signup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_signup2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_signup2);
        jButton_signup2.setBounds(150, 400, 210, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 100, 490, 490);

        jButton_signup1.setBackground(new java.awt.Color(255, 255, 255));
        jButton_signup1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_signup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffeshop/home.png"))); // NOI18N
        jButton_signup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_signup1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_signup1);
        jButton_signup1.setBounds(30, 20, 70, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffeshop/back_medum.jpeg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -30, 800, 680);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 40, 51, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_signupActionPerformed
        // TODO add your handling code here:
      Operations.OpenNew(this, new SignIn());
            
    }//GEN-LAST:event_jButton_signupActionPerformed

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_passwordActionPerformed

    private void jTextField_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phoneActionPerformed

    private void jComboBox_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_cityActionPerformed

    private void jRadioButton_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_maleActionPerformed

    private void jRadioButton_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_femaleActionPerformed

    private void jRadioButton_maleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton_maleMouseClicked
        // TODO add your handling code here:
        if(jRadioButton_male.isSelected())
        {
            jRadioButton_female.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton_maleMouseClicked

    private void jRadioButton_femaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton_femaleMouseClicked
        // TODO add your handling code here:
         if(jRadioButton_female.isSelected())
        {
            jRadioButton_male.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton_femaleMouseClicked

    private void jButton_signup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_signup1ActionPerformed
        // TODO add your handling code here:
        Operations.OpenNew(this, new HomePage());
    }//GEN-LAST:event_jButton_signup1ActionPerformed

    private void jButton_signup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_signup2ActionPerformed
        // TODO add your handling code here:
          if(
                (jTextField_UserName.getText().toString().equals(""))
                ||
                 (jTextField_name.getText().toString().equals(""))
                ||
                 (jTextField_phone.getText().toString().equals(""))
                ||
                 (jPasswordField_password.getText().toString().equals(""))
                )
        {
            Operations.openRequied();
        }
        else
        {
            Customer customer=new Customer();
            customer.setCustomerName(jTextField_name.getText().toString());
            try
            {
            customer.setContactNo(Integer.parseInt(jTextField_phone.getText().toString()));
            }
            catch(Exception exception)
            {
                Operations.openErrorIntRequied();
                return;
            }
           if((!jRadioButton_male.isSelected())&&(jRadioButton_male.isSelected()))
           {
              Operations.openErrorGenderRequied();
                return; 
           }
            char gender='M';
            if(jRadioButton_male.isSelected())
            {
                customer.setGender('M');
            }
            else
            {
               customer.setGender('F'); 
            }
            customer.setCity(jComboBox_city.getSelectedItem().toString());
            UserCoffe userCoffe=new UserCoffe(jTextField_UserName.getText().toString(),jPasswordField_password.getText().toString(),1,1);
            customer.setUserCoffe(userCoffe);
            try
            {
              int id=  customer.addNew();
              userCoffe.setCustomerId(id);
              userCoffe.setRole(2);
              userCoffe.addNew();
              Operations.SuccessRegister();
            }
            catch(Exception exception)
            {
                 Operations.openErrorDataBase();
            }
        }
    }//GEN-LAST:event_jButton_signup2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_signup;
    private javax.swing.JButton jButton_signup1;
    private javax.swing.JButton jButton_signup2;
    private javax.swing.JComboBox<String> jComboBox_city;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JRadioButton jRadioButton_male;
    private javax.swing.JTextField jTextField_UserName;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_phone;
    // End of variables declaration//GEN-END:variables
}
